@url=http://localhost
@port=5000
@host={{url}}:{{port}}

POST  {{host}}/api/airtable/getAllRecord
content-type: application/json

{
    "wfId": "18"
}    
####
POST  {{host}}/api/airtable/getRecord
content-type: application/json

{
    "wfId": "13",
    "recordId":"recPzPfesMi5MPGw0"
}    
####
POST  {{host}}/api/airtable/createRecord
content-type: application/json

{
    "wfId": "14",
    "name":"ash",
    "notes":"notes ash",
    "status":"Todo"
}    
####
POST  {{host}}/api/airtable/updateRecord
content-type: application/json

{
    "wfId": "15",
    "name":"ash updated",
    "notes":"notes ash updated",
    "status":"Todo",
    "recordId":"recrP2pwewxSbgRmw"
}    
####
POST  {{host}}/api/airtable/deleteRecord
content-type: application/json

{
    "wfId": "4",
    "recordId":"receXaVmSygdSkA2c"
}  
####

POST  {{host}}/api/airtable/findRecordWithEmail
content-type: application/json

{
    "wfId": "4",
    "recordId":"receXaVmSygdSkA2c",
    "email":"mooreaaliyah0119@gmail.com"
}  
####
GET   {{host}}/api/airtable/startWorkerAirTable
content-type: application/json

####
POST  http://localhost:5000/api/airtable/processPendingScores
content-type: application/json

{
    "wfId": "pps-53"
}
