@url=http://104.197.47.223
@port=5001
@host={{url}}:{{port}}
@idToken=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlRZT2dnXy01RU9FYmxhWS1WVlJZcVZhREFncHRuZktWNDUzNU1aUEMwdzAifQ.eyJpYXQiOjE2OTA5MzUxNzgsImF1ZCI6IkJLdzhoZ0lQRE1sM3A2YmNZWWxaZ2RYU29Jckx5Sml2dG9aV2NsZDQwd3NOLUFNLVhVQU9raUktQVR2UUdKdTl4NmtSVngzYUd0ZEtRZzNFTWhNX0JyRSIsIm5vbmNlIjoiMDNkOGVkMmU3YjZjNjY1ZjY2OTdjOTQwMWQxYzJiMTFmNWIzYzczMDUxZWRjODMyYTJiZTdkZjFlMGVmYjA5ZDlhIiwiaXNzIjoiaHR0cHM6Ly9hcGkub3BlbmxvZ2luLmNvbSIsIndhbGxldHMiOlt7InB1YmxpY19rZXkiOiI5ZjFlZjYyNmU4MmQyYTczNGRkMmRlYzA3OWMwOTIzODcyZTdlYzFlNjYyM2IxNDYwNzBjZTg0MWU1ZGExN2I5IiwidHlwZSI6IndlYjNhdXRoX2FwcF9rZXkiLCJjdXJ2ZSI6ImVkMjU1MTkifV0sImVtYWlsIjoibmFtQGRydXNzZWxsai5jb20iLCJuYW1lIjoibmFtQGRydXNzZWxsai5jb20iLCJ2ZXJpZmllciI6InRvcnVzIiwidmVyaWZpZXJJZCI6Im5hbUBkcnVzc2VsbGouY29tIiwiYWdncmVnYXRlVmVyaWZpZXIiOiJ0a2V5LWF1dGgwLWVtYWlsLXBhc3N3b3JkbGVzcy1scmMiLCJleHAiOjE2OTEwMjE1Nzh9.cjDiSQOxpuwCqiHNnSbawCCeCNV2bY47382AzEQdiAMqB9MiiiJGehq67Z9nAIcwdIyuoXyZeEfeQmbqAs2cpw

POST {{host}}/api/mint/createMint
content-type: application/json
id-token: {{idToken}}

{
    "wfId": "ash-24",
    "name": "ash-16 name ",
    "description":"ash-16desc", 
    "fileName":"designity.png",
    "role":"admin"
}
###
GET {{host}}/api/mint/getMintedTokenData/mint-ash-24
###
GET {{host}}/api/mint/getUpdatedMintTokenData/mint-ash-20
###
POST {{host}}/api/mint/updateMint
content-type: application/json
id-token: {{idToken}}

{
    "wfId": "ash-20",
    "name": "name ash updated ",
    "description":"updated desc",
    "fileName":"designity.png",
    "role":"admin",
    "mintAddress":"5jTrekCe95fwXh31Pq7k6BqNKbKYYcNCULwrE5RrEXpU"    
}
###

##//ASH--------------------------------->

POST {{host}}/api/mint/getAllNFT
content-type: application/json
id-token:{{idToken}} 

{
    "wfId": "a-02"
}
###
GET {{host}}/api/mint/checkGetAllNFTs/user-a-02
###

POST  {{host}}/api/mint/checkUserThenCreateNft
content-type: application/json
id-token:{{idToken}} 

{
    "wfId": "a-04"
}

###

GET {{host}}/api/mint/returnDataFromCheckUserThenCreateNft/user-a-04
