@url=http://104.197.47.223
@port=5000
@host={{url}}:{{port}}
@idToken=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlRZT2dnXy01RU9FYmxhWS1WVlJZcVZhREFncHRuZktWNDUzNU1aUEMwdzAifQ.eyJpYXQiOjE2OTE1OTAzNjgsImF1ZCI6IkJOX09sM3V5U3psZV9nSzdBWENjVzA1aXFkYUt5ZFVUbjNTUXJDRmt6NTJFNlpXZGFfWG45WUVzbjRuUktqR2pyd05YYzkxQWJiR3RNcVNHOUx0Nlp0NCIsIm5vbmNlIjoiMDI1YjdmMDZkNzFkZGUwMWI5ODFiMDFiYjQzOGJiOGQzMWNiODk4ZmNkNmVhNDA1NDgxNzE2NGU2OGFlNjgyZWRiIiwiaXNzIjoiaHR0cHM6Ly9hcGkub3BlbmxvZ2luLmNvbSIsIndhbGxldHMiOlt7InB1YmxpY19rZXkiOiI1MjQyZjc3OTNmMDI4OGVmMzU0NWE1N2M3ODdmODkxZWNhZWNmNGJkNmRmZWM5OTYxOGIyOGYxMWY1ZjRjNTBkIiwidHlwZSI6IndlYjNhdXRoX2FwcF9rZXkiLCJjdXJ2ZSI6ImVkMjU1MTkifV0sImVtYWlsIjoibWVoZGlkZWhkYXI4OUBnbWFpbC5jb20iLCJuYW1lIjoibWVoZGlkZWhkYXI4OUBnbWFpbC5jb20iLCJ2ZXJpZmllciI6InRvcnVzIiwidmVyaWZpZXJJZCI6Im1laGRpZGVoZGFyODlAZ21haWwuY29tIiwiYWdncmVnYXRlVmVyaWZpZXIiOiJ0a2V5LWF1dGgwLWVtYWlsLXBhc3N3b3JkbGVzcy1scmMiLCJleHAiOjE2OTE2NzY3Njh9.0xldIAzJsHm7PasXin44iua__ytoBJq52iunK8av02b7Mo4LfCeI_LVEjnXFPK8IVf2Xr2BAfDvUbXNY-Bbwew
POST {{host}}/api/mint/createMint
content-type: application/json
id-token: {{idToken}}

{
    "wfId": "ash-24",
    "name": "ash-16 name ",
    "description":"ash-16desc", 
    "fileName":"designity.png",
    "role":"admin"
}
###
GET {{host}}/api/mint/getMintedTokenData/mint-ash-24
###
GET {{host}}/api/mint/getUpdatedMintTokenData/mint-ash-20
###
POST {{host}}/api/mint/updateMint
content-type: application/json
id-token: {{idToken}}

{
    "wfId": "ash-20",
    "name": "name ash updated ",
    "description":"updated desc",
    "fileName":"designity.png",
    "role":"admin",
    "mintAddress":"5jTrekCe95fwXh31Pq7k6BqNKbKYYcNCULwrE5RrEXpU"    
}
###

##//ASH--------------------------------->

POST {{host}}/api/mint/getAllNFT
content-type: application/json
id-token:{{idToken}} 

{
    "wfId": "a-02"
}
###
GET {{host}}/api/mint/checkGetAllNFTs/user-a-02
###

POST  {{host}}/api/mint/checkUserThenCreateNft
content-type: application/json
id-token:{{idToken}} 

{
    "wfId": "a-27"
}

###

GET {{host}}/api/mint/returnDataFromCheckUserThenCreateNft/user-a-27

###
POST  {{host}}/api/mint/getMagicLinkFromAirtable
content-type: application/json
id-token:{{idToken}} 

{
    "wfId": "a-26"
}

###
GET {{host}}/api/mint/returnLogedinUserAiritableMagigLink/user-a-26