@url=https://api.designity.software
@port=
@host={{url}}:{{port}}
@idToken=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlRZT2dnXy01RU9FYmxhWS1WVlJZcVZhREFncHRuZktWNDUzNU1aUEMwdzAifQ.eyJpYXQiOjE2ODkyMTQ2MTUsImF1ZCI6IkJLdzhoZ0lQRE1sM3A2YmNZWWxaZ2RYU29Jckx5Sml2dG9aV2NsZDQwd3NOLUFNLVhVQU9raUktQVR2UUdKdTl4NmtSVngzYUd0ZEtRZzNFTWhNX0JyRSIsIm5vbmNlIjoiMDM0NzM3M2UzZDRkNWY0MTRiYmNjOWIyYzQxZWIwOGQ3MWM4ZmU5YjE5ODEwMDZjOTY0MTNkN2VlYzMzYjcyMGZmIiwiaXNzIjoiaHR0cHM6Ly9hcGkub3BlbmxvZ2luLmNvbSIsIndhbGxldHMiOlt7InB1YmxpY19rZXkiOiI4YjhjYTNjMDAwMmVmM2Q2NDAxZTM3ZjUwYmY1OGU2MGE4MGQ3ZGMyYzNlODFmNWI0OTA4ODk3YjY3MjRlNDc1IiwidHlwZSI6IndlYjNhdXRoX2FwcF9rZXkiLCJjdXJ2ZSI6ImVkMjU1MTkifV0sImVtYWlsIjoiYW1pcnNoYXJpZmljb0BnbWFpbC5jb20iLCJuYW1lIjoiYW1pcnNoYXJpZmljb0BnbWFpbC5jb20iLCJ2ZXJpZmllciI6InRvcnVzIiwidmVyaWZpZXJJZCI6ImFtaXJzaGFyaWZpY29AZ21haWwuY29tIiwiYWdncmVnYXRlVmVyaWZpZXIiOiJ0a2V5LWF1dGgwLWVtYWlsLXBhc3N3b3JkbGVzcy1scmMiLCJleHAiOjE2ODkzMDEwMTV9.n7MSZUnqh-xWmRs3VwDJTm9Qq3JThpBsmL5bp0KgfAcnW8UHUKl9qX9aItnL5-1D0ROAJc3TcriASTFnhw1qdA

POST {{host}}/api/user/checkEmail
content-type: application/json

{
    "wfId": "44",
    "email": "amirsharifico@gmail.com"
}
###
GET {{host}}/api/user/getAllUserDTO/user-44
###
POST {{host}}/api/user/getAllNFT
content-type: application/json
id-token:{{idToken}} 

{
    "wfId": "a-02"
}
###
GET {{host}}/api/user/checkGetAllNFTs/user-a-02

