[features]
seeds = true
skip-lint = false
[programs.localnet]
growth = "A4DzHwqsxB3BbaPXWYMdQzqwigZGysTyw4HFuk3mHgts"
[programs.devnet]
growth = "97d8t22JenPAwR85PZEXvc4gkvtAMZR9Ct7xuY11a2X8"
[programs.mainnet]
growth = "97d8t22JenPAwR85PZEXvc4gkvtAMZR9Ct7xuY11a2X8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/Users/air/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
