[features]
seeds = true
skip-lint = false
[programs.localnet]
growth = "86kpZGxTEDUF3VShNZfykKM8ow1TEeuHEzJ3tduLFyQY"
[programs.devnet]
growth = "86kpZGxTEDUF3VShNZfykKM8ow1TEeuHEzJ3tduLFyQY"
[programs.mainnet]
growth = "86kpZGxTEDUF3VShNZfykKM8ow1TEeuHEzJ3tduLFyQY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/air/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
