[features]
seeds = true
skip-lint = false
[programs.localnet]
growth = "CuoBzVYwdvuGPbFZyd391MkFuPLYZ6absTpv7ibWu1GZ"
[programs.devnet]
growth = "CuoBzVYwdvuGPbFZyd391MkFuPLYZ6absTpv7ibWu1GZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
# cluster = "devnet"
wallet = "/home/mehdidehdar89/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
