qqPOST http://34.123.25.77:5000/api/test/validation?workFlowId=
content-type: application/json
id-token: 

{
    "wfId": "m11",
    "name":"mr.dehdar@g.com",
    "fileName":"designity.png",
    "role":"admin"
}

########

POST http://104.197.47.223:5000/api/test/call_parent
content-type: application/json
id-token: 

{
    "wfId": "parent1"
}


#####
POST http://localhost:5000/api/test/growth
content-type: application/json

{
    
}
#####
GET http://localhost:5000/api/mint/getMagicLinkFromAirtable
content-type: application/json
id-token: 

{
    
}