POST http://34.123.25.77:5001/api/user/checkEmail
content-type: application/json

{
    "wfId": "44",
    "email": "amirsharifico@gmail.com"
}
###
GET http://34.123.25.77:5001/api/user/getAllNFT/user-a-01
###
POST http://34.123.25.77:5001/api/user/getAllNFT
content-type: application/json
id-token: 

{
    "wfId": "a-01"
}
###
GET http://34.123.25.77:5001/api/user/getAllUserDTO/user-44