POST http://34.123.25.77:5000/api/mint/createMint
content-type: application/json
id-token: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlRZT2dnXy01RU9FYmxhWS1WVlJZcVZhREFncHRuZktWNDUzNU1aUEMwdzAifQ.eyJpYXQiOjE2ODgwMzMxMjAsImF1ZCI6IkJFc3NHT0ZaRFVTT1BwelhadmRTUTAyblhCUVVDQTEzRVE3cElJZFBmbmljaEc1NUpSOGtVMHBVNXpSR28teEp1emEwU1VsNUd4OWUyUFhPdXZNejFvZyIsIm5vbmNlIjoiMDIzYzNmZTk5OTA5ZjNhMjhhYWJmM2E0MWIyYTc5MzY0YTNlNTdlYmI4MThjOTYyNDMyZjA4MTIyNTZhNDRmN2E1IiwiaXNzIjoiaHR0cHM6Ly9hcGkub3BlbmxvZ2luLmNvbSIsIndhbGxldHMiOlt7InB1YmxpY19rZXkiOiJiYzQ4YTIzMmRkMjQwYjExZTgxNGJlNWU3MTA1NDMyN2I0ODNlYTQ5YTQyMzQ3ZjY3NDU0ZGNmZDFiNDM3ODJiIiwidHlwZSI6IndlYjNhdXRoX2FwcF9rZXkiLCJjdXJ2ZSI6ImVkMjU1MTkifV0sImVtYWlsIjoibWVoZGlkZWhkYXI4OUBnbWFpbC5jb20iLCJuYW1lIjoibWVoZGlkZWhkYXI4OUBnbWFpbC5jb20iLCJ2ZXJpZmllciI6InRvcnVzIiwidmVyaWZpZXJJZCI6Im1laGRpZGVoZGFyODlAZ21haWwuY29tIiwiYWdncmVnYXRlVmVyaWZpZXIiOiJ0a2V5LWF1dGgwLWVtYWlsLXBhc3N3b3JkbGVzcy1scmMiLCJleHAiOjE2ODgxMTk1MjB9.q8bQZSmAXPZVtW3OYTMLVsR6Mw4Uan2da8uDqMRWsTdCqa9vZ8SfKsiczD4kV1v-3gdUdqEBy2654ARvEYOEHA

{
    "wfId": "m11",
    "name": "mehdi2 test new",
    "description":"des test2 new",
    "fileName":"designity.png",
    "role":"admin"
}