POST http://34.123.25.77:5001/api/mint/updateMint
content-type: application/json
id-token: 
{
    "wfId": "a-299",
    "name": "name ash updated ",
    "description":"updated desc",
    "fileName":"designity.png",
    "role":"admin",
    "mintAddress":"FHk3KYbk4MjpfoATszfeYMY6P82CSRMJm8vUzsLofdkj"    
}